name: Linux SDL Project Build

on:
  push:
    branches: [ main ]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
          config:
            - build_type: debug

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Install SDL Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          libsdl2-dev \
          libsdl2-image-dev \
          libsdl2-mixer-dev \
          libsdl2-ttf-dev \
          build-essential

    - name: Generate Project Files
      run: ./Vendor/bin/Linux/premake5 gmake2

    - name: Build Project with AddressSanitizer
      run: |
        make config=debug_x64 CFLAGS="-fsanitize=address" LDFLAGS="-fsanitize=address"
      working-directory: ./Pacman
